### ISSUE TITLE
Did not follow through with implementing roomAssignment addition everywhere.

### ISSUE THREAD

**Issue by Jacoby04** [casal033/UMM3601ursamajor#10]
roomAssignment was added to the model but not everywhere submissions are affected was updated. For example, a new submission does not receive a roomAssignment field (even though it should likely just default to an empty string). I'll make the assumption that it was also not thought through for resubmission.

**Comment by casal033** [comment]
Talking with our customer Stephanie, we decides room assignment was not needed. So focus on finishing stories!
