### ISSUE TITLE
Formatting whitespace is being minified

### ISSUE THREAD

**Issue by bman4789** [casal033/UMM3601ursamajor#15]
On the Heroku site, the submission list buttons don't have spaces between them. When Grunt builds the production version of the site, these spaces are being minfied (removed because it thinks they are not required). This can be fixed by using the  escape character for a space, "&#32;" instead of the " ". Editing the gruntfile to include spaces may be an option too, but it'd be a much more time consuming fix to figure out how to do.

**Comment by Jacoby04** [comment]
This was fixed with commit 1003. Still need to check it on Heroku.

**Comment by bman4789** [comment]
The issue only comes up if you run 'grunt build' and serve that. To fix you'll probably have to replace " " with the space escape character "&nbsp;"
