### ISSUE TITLE
Creating comment issue

### ISSUE THREAD

**Issue by lehet005** [casal033/UMM3601ursamajor#18]
Sometimes, when you create a comment, it comes up with an error and doesn't post to the comment section.  This happened to me when I was logged in as "reviewer@reviewer.com".
It happened on both submissions that I was trying to comment on.  After awhile of force commenting, it would eventually work.  (this was without highlighting any text)

**Comment by ScribblesandFlapjacks** [comment]
Fixed by adding a case to check for null selections
