### ISSUE TITLE
Presenters can make submissions under false name/email.

### ISSUE THREAD

**Issue by Jacoby04** [casal033/UMM3601ursamajor#20]
As it stands, a person can currently submit a submission with another person's name and email. We feel that functionality should not be allowed for a default user. Might want to consult the customer for the best solution.
Options:
-Perform a check if they don't have privileges that the name matches whoever is logged in as appropriate.
-Autofill those categories with name and email of who is logged in.

**Comment by casal033** [comment]
Steph Answer: 3.  This confused me....not sure what you mean.....I'm not sure why someone would make a false submission...the only folks that should be submitting would be presenting.  I assume that anyone other than the administrator, adviser, or co-chair would be a student...I can not see a reason for sabotage...
