### ISSUE TITLE
Check the Submission Form Editor

### ISSUE THREAD

**Issue by Jacoby04** [casal033/UMM3601ursamajor#22]
Just like we had to go through the original submission form and make sure the data being submitted was correct and matched the model, we should check that the submission form editor still has all the text bodies from the submission form and is able to edit all of them correctly.
1. Ensure model has everything needed from submission form.
2. Ensure controller and html of editor contain all fields from model where appropriate.

**Comment by lehet005** [comment]
Checked it out and it looks all good!
