### ISSUE TITLE
Emails in Details View?

### ISSUE THREAD

**Issue by Jacoby04** [casal033/UMM3601ursamajor#24]
Question for the customer... Do they want to see the emails for the presenter, copresenter, adviser, coadviser or some subset of those within the details view?

**Comment by casal033** [comment]
Steph Answer: 1.  Emails do not need to be here.  As long as they are somewhere...(meaning if I can't find an email I know where to find it in the profile, etc).  If you want to put it here you can, but doesn't need to be.
